export type GetWorkspaceProjectsResponse = {
    id: number;
    workspace_id: number;
    client_id: number | null;
    name: string;
    is_private: boolean;
    active: boolean;
    at: string;
    created_at: string;
    server_deleted_at: string | null;
    color: string;
    billable: boolean;
    template: boolean;
    auto_estimates: boolean;
    estimated_hours: number | null;
    estimated_seconds: number | null;
    rate: number | null;
    rate_last_updated: string | null;
    currency: string;
    recurring: boolean;
    template_id: number | null;
    recurring_parameters: any | null;
    fixed_fee: number | null;
    actual_hours: number;
    actual_seconds: number;
    total_count: number;
    client_name: string | null;
    can_track_time: boolean;
    start_date: string;
    status: string;
    wid: number;
    cid: number | null;
    pinned: boolean;
}[];

export type GetWorkspaceProjectsOptions = {
    active?: boolean | 'both';
    since?: number;
    billable?: boolean;
    user_ids?: number[];
    client_ids?: number[];
    group_ids?: number[];
    project_ids?: number[];
    statuses?: string[];
    name?: string;
    page?: number;
    sort_field?: string;
    sort_order?: string;
    only_templates: boolean;
    only_me?: boolean;
    per_page?: number;
};
