export type GetWorkspaceProjectsResponse = {
    id: number;
    workspace_id: number;
    client_id: number | null;
    name: string;
    is_private: boolean;
    active: boolean;
    at: string;
    created_at: string;
    server_deleted_at: string | null;
    color: string;
    billable: boolean;
    template: boolean;
    auto_estimates: boolean;
    estimated_hours: number | null;
    estimated_seconds: number | null;
    rate: number | null;
    rate_last_updated: string | null;
    currency: string;
    recurring: boolean;
    template_id: number | null;
    recurring_parameters: any | null;
    fixed_fee: number | null;
    actual_hours: number;
    actual_seconds: number;
    total_count: number;
    client_name: string | null;
    can_track_time: boolean;
    start_date: string;
    status: string;
    wid: number;
    cid: number | null;
    pinned: boolean;
}[];

export type GetWorkspaceProjectsOptions = {
    active?: boolean | 'both';
    since?: number;
    billable?: boolean;
    user_ids?: number[];
    client_ids?: number[];
    group_ids?: number[];
    project_ids?: number[];
    statuses?: string[];
    name?: string;
    page?: number;
    sort_field?: string;
    sort_order?: string;
    only_templates: boolean;
    only_me?: boolean;
    per_page?: number;
};

export type GetWorkspaceTimeEntriesResponse = {
    user_id: number;
    username: string;
    project_id: number;
    task_id: number | null;
    billable: boolean;
    description: string;
    tag_ids: number[];
    billable_amount_in_cents: number;
    hourly_rate_in_cents: number;
    currency: string;
    time_entries: {
        id: number;
        seconds: number;
        start: string;
        stop: string;
        at: string;
        at_tz: string;
    }[];
    row_number: number;
}[];

export type GetWorkspaceTimeEntiresOptions = {
    billable?: boolean;
    client_ids?: (number | null)[];
    description?: string;
    endTime?: string;
    end_date?: string;
    enrich_response?: boolean;
    first_id?: number;
    first_row_number?: number;
    first_timestamp?: number;
    group_ids?: number[];
    grouped?: boolean;
    hide_amounts?: boolean;
    max_duration_seconds?: number;
    min_duration_seconds?: number;
    order_by?: 'date' | 'user' | 'duration' | 'description' | 'last_update';
    order_dir?: 'ASC' | 'DESC';
    page_size?: number;
    project_ids?: (number | null)[];
    rounding?: number;
    rounding_minutes?: 0 | 1 | 5 | 6 | 10 | 12 | 15 | 30 | 60 | 240;
    startTime?: string;
    start_date?: string;
    tag_ids?: (number | null)[];
    task_ids?: (number | null)[];
    time_entry_ids?: number[];
    user_ids?: number[];
};

export type GetWorkspaceUsersReturn = {
    id: number;
    uid: number;
    user_id: number;
    wid: number;
    workspace_id: number;
    admin: boolean;
    organization_admin: boolean;
    workspace_admin: boolean;
    active: boolean;
    email: string;
    timezone: string;
    '2fa_enabled': boolean;
    inactive: boolean;
    at: string; // ISO timestamp
    name: string;
    group_ids: number[] | null;
    rate: number | null;
    rate_last_updated: string | null;
    labor_cost: number | null;
    labor_cost_last_updated: string | null;
    invite_url: string | null;
    invitation_code: string | null;
    avatar_file_name: string | null;
    working_hours_in_minutes: number | null;
    role: string;
    view_edit_billable_rates: boolean;
    view_edit_labor_costs: boolean;
    is_direct: boolean;
}[];

export type GetWorkspaceUsersOptions = {
    page?: number;
    per_page?: number;
    custom_rates?: boolean;
    active?: boolean;
    name?: string;
    search?: string;
};
